version: 2
jobs:
 build:
   docker:
     - image: docker:18.06.3-ce
   steps:
     - checkout
     - setup_remote_docker:
         docker_layer_caching: true
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t accelforce/odakyudon:latest .
     - run: docker push accelforce/odakyudon:latest
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
